# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"

  desc "Upload a new version to the Google Play"
  lane :beta do
    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges"
    )
    version_code = sh("grep ^version ../pubspec.yaml | cut -d'+' -f2  | tr -d '\n'").to_i
    upload_to_play_store(
       version_code: version_code,
       skip_upload_aab: true,
       apk: "build/app/outputs/apk/release/app-release.apk",
       track: "beta"
    )
  end
end


platform :ios do
  before_all do
    cocoapods(podfile: './ios/Podfile')
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    get_certificates

    get_provisioning_profile
    build_app(
      scheme: "Runner",
      workspace: "ios/Runner.xcworkspace",
      include_bitcode: true
    )

    pilot
  end
end


