# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Upload a new version to the Google Play"
  lane :supply do
    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges"
    )
    version_code = sh("grep ^version ../pubspec.yaml | cut -d'+' -f2  | tr -d '\n'").to_i
    upload_to_play_store(
       version_code: version_code,
       skip_upload_aab: true,
       apk: "build/app/outputs/apk/release/app-release.apk",
       track: "beta"
    )
  end
end


platform :ios do
  before_all do
    cocoapods(podfile: './ios/Podfile')

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sync_code_signing(type: "appstore")

    build_app(
      scheme: "Runner",
      workspace: "ios/Runner.xcworkspace",
      include_bitcode: true
    )

    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


