name: CI

on: [push]

jobs:
  build:
    runs-on: macos
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
      - run: flutter pub get
      - name: Setup signing
        env:
          androidSigningKeyBase64: ${{ secrets.androidSigningKeyBase64 }}
          androidSigningStorePassword: ${{ secrets.androidSigningStorePassword }}
          androidSigningKeyPassword: ${{ secrets.androidSigningKeyPassword }}
          androidSigningKeyAlias: ${{ secrets.androidSigningKeyAlias }}
          playStoreApiJsonBase64: ${{ secrets.playStoreApiJsonBase64 }}
        run: |
          echo ${playStoreApiJsonBase64} | base64 -d > googleplay.json
          cd android
          echo ${androidSigningKeyBase64} | base64 -d > app/keystore.jks
          echo "storeFile=keystore.jks" > key.properties
          echo "storePassword=$androidSigningStorePassword" >> key.properties
          echo "keyPassword=$androidSigningKeyPassword" >> key.properties
          echo "keyAlias=$androidSigningKeyAlias" >> key.properties
#      - run: flutter build apk --release
#      - name: Fastlane upload to PlayStore
#        uses: maierj/fastlane-action@v1.2.0
#        with:
#          lane: 'android beta'
#          options: '{ "apk": "../build/app/outputs/apk/release/app-release.apk" }'
#      - run: flutter build ios --release --no-codesign
      - name: Fastlane upload TestFlight (iOS)
        env:
          FASTLANE_USER: "menk@mestrona.net"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          # MATCH_GIT_BASIC_AUTHORIZATION is "githubuser:githubtoken" in base64 encoded string
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        uses: maierj/fastlane-action@v1.2.0
        with:
          lane: 'ios beta'
